services:
  frontend:
    build: ./recipe-fe
    ports:
      - '3000:3000'

  backend:
    build: ./recipe-be
    ports:
      - '8000:8000'
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - .env

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.runCommand('ping').ok"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/?authSource=admin
      ME_CONFIG_BASICAUTH: false

volumes:
  mongo_data:
